export const TOTAL_PORTFOLIO_WEIGHT_TARGET = 100
export const PROPOSED_TOTAL_PORTFOLIO_WEIGHT_TOLERANCE_POINTS = 0.5

export const PROSPECTUS_TOTAL_EQUITY_WEIGHT_MIN = 85
export const PROSPECTUS_TOTAL_EQUITY_WEIGHT_MAX = 95
export const PROPOSED_TOTAL_EQUITY_WEIGHT_GREEN_MIN = 86
export const PROPOSED_TOTAL_EQUITY_WEIGHT_GREEN_MAX = 94

export const PROSPECTUS_TPP_WEIGHT_MIN = 5
export const PROSPECTUS_TPP_WEIGHT_MAX = 15

export const PROSPECTUS_STOCK_COUNT_MIN = 16
export const PROSPECTUS_STOCK_COUNT_MAX = 30

export const PROSPECTUS_SINGLE_STOCK_MAX_WEIGHT = 10
export const PROPOSED_SINGLE_STOCK_AMBER_MARGIN_POINTS = 1

export const PROSPECTUS_SECTOR_CONCENTRATION_MAX = 30
export const PROPOSED_SECTOR_CONCENTRATION_GREEN_MAX = 27

export const PROPOSED_MAX_DRAWDOWN_AMBER_MARGIN_POINTS = 1
export const PROPOSED_CONSERVATIVE_RISK_INCREASE_THRESHOLD_POINTS = 0.2
export const PROPOSED_BALANCED_RISK_INCREASE_THRESHOLD_POINTS = 0.5
